swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /playlist/deezer/{uid}:
    get:
      tags:
      - playlist/deezer
      description: get user by uid
      operationId: DeezerController.Get
      parameters:
      - in: path
        name: uid
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: :uid is empty
  /playlist/spotify/{uid}:
    get:
      tags:
      - playlist/spotify
      description: get user by uid
      operationId: SpotifyController.Get
      parameters:
      - in: path
        name: uid
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.User'
        "403":
          description: :uid is empty
definitions:
  models.User:
    title: User
    type: object
tags:
- name: playlist/spotify
  description: |
    SpotifyController to work around with */spotify/* requests
- name: playlist/deezer
  description: |
    Operations about Users
